use_frameworks!

platform :ios, '10.0'

target 'YDPreLoader_Example' do
  pod 'YDPreLoader', :path => '../'

  target 'YDPreLoader_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
